### ISSUE TITLE
How did you get the http server working from JupyterLab?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/low-touch-hubs#15]
We ran into issues around previewing Jupyter Books for the Turing Way / Jupyter Book jupytercon tutorial (https://github.com/martinagvilas/jupytercon_tutorial/issues/14) I wonder if this pattern could be used there as well for Binder?

**Comment by choldgraf** [comment]
(on that note, I wonder if we should offer to the turing way to run infrastructure for their workshop, if they aren't able to get things working on Binder...it's just a one-day workshop)

**Comment by colliand** [comment]
Yes. We should do that!

**Comment by choldgraf** [comment]
I figured it out with this PR: https://github.com/martinagvilas/jupytercon_tutorial/pull/39
